2024-09-22 01:26:54,445 - process_daily_narrative - INFO - DEBUGGING THIS APP
2024-09-22 01:26:54,445 - process_daily_narrative - INFO - Python executable: /Users/raghuvar/Code/GoodSide-organized/code/luleo/process_daily_narrative/.venv/bin/python
2024-09-22 01:26:54,445 - process_daily_narrative - INFO - Python version: 3.9.19 (main, May  6 2024, 14:46:57) 
[Clang 14.0.6 ]
2024-09-22 01:26:54,445 - process_daily_narrative - INFO - Virtual environment: /Users/raghuvar/Code/GoodSide-organized/code/luleo/process_daily_narrative/.venv
2024-09-22 01:26:54,445 - process_daily_narrative - INFO - Testing this - Raghuvars-MBP.fios-router.home
2024-09-22 02:25:09,826 - process_daily_narrative - INFO - DEBUGGING THIS APP
2024-09-22 02:25:09,826 - process_daily_narrative - INFO - Python executable: /Users/raghuvar/Code/GoodSide-organized/code/luleo/process_daily_narrative/.venv/bin/python
2024-09-22 02:25:09,826 - process_daily_narrative - INFO - Python version: 3.9.19 (main, May  6 2024, 14:46:57) 
[Clang 14.0.6 ]
2024-09-22 02:25:09,826 - process_daily_narrative - INFO - Virtual environment: /Users/raghuvar/Code/GoodSide-organized/code/luleo/process_daily_narrative/.venv
2024-09-22 02:25:09,826 - process_daily_narrative - INFO - Testing this - Raghuvars-MBP.fios-router.home
2024-09-22 02:26:14,909 - process_daily_narrative - INFO - Received request
2024-09-22 02:26:14,910 - process_daily_narrative - INFO - Request method: POST
2024-09-22 02:26:14,910 - process_daily_narrative - INFO - Request headers: Host: 127.0.0.1:8080
User-Agent: python-requests/2.32.3
Accept-Encoding: gzip, deflate, br, zstd
Accept: */*
Connection: keep-alive
Content-Length: 50
Content-Type: application/json


2024-09-22 02:26:14,912 - process_daily_narrative - INFO - Request data: b'{"REQUEST_TYPE": "GET_LULEO_PROMPT", "PARAMS": {}}'
2024-09-22 02:26:14,912 - process_daily_narrative - INFO - Request JSON: {'REQUEST_TYPE': 'GET_LULEO_PROMPT', 'PARAMS': {}}
2024-09-22 02:26:14,912 - process_daily_narrative - INFO - REQUEST_TYPE: GET_LULEO_PROMPT
2024-09-22 02:26:14,912 - process_daily_narrative - INFO - PARAMS: {}
2024-09-22 02:26:14,912 - process_daily_narrative - INFO - Applying function: get_luleo_prompt
2024-09-22 02:26:15,199 - process_daily_narrative - ERROR - Error in GET_LULEO_PROMPT {}
2024-09-22 02:26:15,202 - process_daily_narrative - ERROR - Traceback (most recent call last):
  File "/Users/raghuvar/Code/GoodSide-organized/code/luleo/process_daily_narrative/main.py", line 52, in call_default_cloud_run
    ret_val = func_to_apply(**request_params)
  File "/Users/raghuvar/Code/GoodSide-organized/code/luleo/process_daily_narrative/utils/luleo.py", line 13, in get_luleo_prompt
    summary = get_latest_summary()
  File "/Users/raghuvar/Code/GoodSide-organized/code/luleo/process_daily_narrative/utils/end_of_day_update.py", line 196, in get_latest_summary
    return doc.to_dict()
AttributeError: 'list' object has no attribute 'to_dict'

