2024-10-28 11:15:21,524 - system - INFO - DEBUGGING THIS APP
2024-10-28 11:15:21,524 - system - INFO - Python executable: /Users/raghuvar/Code/GoodSide-organized/code/luleo/process_daily_narrative/.venv/bin/python
2024-10-28 11:15:21,524 - system - INFO - Python version: 3.9.19 (main, May  6 2024, 14:46:57) 
[Clang 14.0.6 ]
2024-10-28 11:15:21,524 - system - INFO - Virtual environment: /Users/raghuvar/Code/GoodSide-organized/code/luleo/process_daily_narrative/.venv
2024-10-28 11:15:21,524 - system - INFO - Testing this - Raghuvars-MBP.fios-router.home
2024-10-28 11:15:26,593 - system - INFO - Received request
2024-10-28 11:15:26,593 - system - INFO - Request method: POST
2024-10-28 11:15:26,593 - system - INFO - Request headers: Host: localhost:8080
User-Agent: python-requests/2.32.3
Accept-Encoding: gzip, deflate, br, zstd
Accept: */*
Connection: keep-alive
Content-Type: application/json
Content-Length: 110


2024-10-28 11:15:26,594 - system - INFO - Request data: b'{"REQUEST_TYPE": "CONTRIBUTE_TEXT", "PARAMS": {"name": "Jack", "message": "I hope Kamala wins the election!"}}'
2024-10-28 11:15:26,594 - system - INFO - Request JSON: {'REQUEST_TYPE': 'CONTRIBUTE_TEXT', 'PARAMS': {'name': 'Jack', 'message': 'I hope Kamala wins the election!'}}
2024-10-28 11:15:26,594 - system - INFO - REQUEST_TYPE: CONTRIBUTE_TEXT
2024-10-28 11:15:26,594 - system - INFO - PARAMS: {'name': 'Jack', 'message': 'I hope Kamala wins the election!'}
2024-10-28 11:15:26,594 - system - INFO - Applying function: contribute_text
2024-10-28 11:15:26,983 - system - INFO - Function returned: (<Response 90 bytes [200 OK]>, 200)
2024-10-28 11:15:26,983 - system - ERROR - Error in CONTRIBUTE_TEXT {'name': 'Jack', 'message': 'I hope Kamala wins the election!'}
2024-10-28 11:15:26,986 - system - ERROR - Traceback (most recent call last):
  File "/Users/raghuvar/Code/GoodSide-organized/code/luleo/process_daily_narrative/main.py", line 55, in call_default_cloud_run
    return jsonify(ret_val)
  File "/Users/raghuvar/Code/GoodSide-organized/code/luleo/process_daily_narrative/.venv/lib/python3.9/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
  File "/Users/raghuvar/Code/GoodSide-organized/code/luleo/process_daily_narrative/.venv/lib/python3.9/site-packages/flask/json/provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
  File "/Users/raghuvar/Code/GoodSide-organized/code/luleo/process_daily_narrative/.venv/lib/python3.9/site-packages/flask/json/provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "/Users/raghuvar/opt/anaconda3/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/raghuvar/opt/anaconda3/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/raghuvar/opt/anaconda3/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/raghuvar/Code/GoodSide-organized/code/luleo/process_daily_narrative/.venv/lib/python3.9/site-packages/flask/json/provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Response is not JSON serializable

2024-10-28 11:15:32,584 - system - INFO - Log file uploaded to GitHub: logs/system/log_2024-10-28.11.15.26.txt
2024-10-28 11:15:37,895 - system - INFO - Log file uploaded to GitHub: logs/llm/log_2024-10-28.11.15.32.txt
2024-10-28 11:18:11,942 - system - INFO - Received request
2024-10-28 11:18:11,943 - system - INFO - Request method: POST
2024-10-28 11:18:11,943 - system - INFO - Request headers: Host: localhost:8080
User-Agent: python-requests/2.32.3
Accept-Encoding: gzip, deflate, br, zstd
Accept: */*
Connection: keep-alive
Content-Type: application/json
Content-Length: 49


2024-10-28 11:18:11,944 - system - INFO - Request data: b'{"REQUEST_TYPE": "CONTRIBUTE_TEXT", "PARAMS": {}}'
2024-10-28 11:18:11,944 - system - INFO - Request JSON: {'REQUEST_TYPE': 'CONTRIBUTE_TEXT', 'PARAMS': {}}
2024-10-28 11:18:11,944 - system - INFO - REQUEST_TYPE: CONTRIBUTE_TEXT
2024-10-28 11:18:11,944 - system - INFO - PARAMS: {}
2024-10-28 11:18:11,944 - system - INFO - Applying function: contribute_text
2024-10-28 11:18:11,944 - system - ERROR - Error in CONTRIBUTE_TEXT {}
2024-10-28 11:18:11,945 - system - ERROR - Traceback (most recent call last):
  File "/Users/raghuvar/Code/GoodSide-organized/code/luleo/process_daily_narrative/main.py", line 51, in call_default_cloud_run
    ret_val = func_to_apply(**request_params)
TypeError: contribute_text() missing 2 required positional arguments: 'name' and 'message'

