2024-10-01 03:30:18,832 - system - INFO - DEBUGGING THIS APP
2024-10-01 03:30:18,832 - system - INFO - Python executable: /usr/local/bin/python
2024-10-01 03:30:18,832 - system - INFO - Python version: 3.9.20 (main, Sep 27 2024, 06:05:20) 
[GCC 12.2.0]
2024-10-01 03:30:18,832 - system - INFO - Virtual environment: None
2024-10-01 03:30:18,833 - system - INFO - Testing this - localhost
2024-10-01 03:30:18,864 - system - INFO - Received request
2024-10-01 03:30:18,864 - system - INFO - Request method: POST
2024-10-01 03:30:18,864 - system - INFO - Request headers: Host: process-daily-narrative-418435618601.us-central1.run.app
Content-Type: application/json
X-Cloudscheduler: true
X-Cloudscheduler-Scheduletime: 2024-09-30T20:30:00-07:00
X-Cloudscheduler-Jobname: hourly_qualia_update
Content-Length: 53
User-Agent: Google-Cloud-Scheduler
X-Cloud-Trace-Context: 24a0258043c5c69ed155c7411f4f1476/12290298272905600185;o=1
Traceparent: 00-24a0258043c5c69ed155c7411f4f1476-aa8fe92994229cb9-01
X-Forwarded-For: 34.98.143.137
X-Forwarded-Proto: https
Forwarded: for="34.98.143.137";proto=https
Accept-Encoding: gzip, deflate, br


2024-10-01 03:30:18,865 - system - INFO - Request data: b'{\n  "REQUEST_TYPE": "QUALIA_UPDATE",\n  "PARAMS": {}\n}'
2024-10-01 03:30:18,865 - system - INFO - Request JSON: {'REQUEST_TYPE': 'QUALIA_UPDATE', 'PARAMS': {}}
2024-10-01 03:30:18,865 - system - INFO - REQUEST_TYPE: QUALIA_UPDATE
2024-10-01 03:30:18,865 - system - INFO - PARAMS: {}
2024-10-01 03:30:18,865 - system - INFO - Applying function: hourly_update
2024-10-01 03:30:18,865 - system - INFO - Updating hourly...
2024-10-01 03:30:19,060 - system - INFO - [[<Aggregation alias=unprocessed_count, value=0.0, readtime=2024-10-01 03:30:19.045642+00:00>]]
2024-10-01 03:30:19,061 - system - INFO - Processing 0 out of 0.0 events for retrieved_reddit_posts
2024-10-01 03:30:19,176 - system - INFO - [[<Aggregation alias=unprocessed_count, value=0.0, readtime=2024-10-01 03:30:19.162620+00:00>]]
2024-10-01 03:30:19,177 - system - INFO - Processing 0 out of 0.0 events for retrieved_articles
2024-10-01 03:30:19,282 - system - ERROR - Error in QUALIA_UPDATE {}
2024-10-01 03:30:19,291 - system - ERROR - Traceback (most recent call last):
  File "/app/main.py", line 51, in call_default_cloud_run
    ret_val = func_to_apply(**request_params)
  File "/app/src/scripts.py", line 18, in hourly_update
    update_qualia()
  File "/app/utils/qualia.py", line 285, in update_qualia
    events_to_process = get_events_to_process()
  File "/app/utils/qualia.py", line 169, in get_events_to_process
    event_dict = doc.to_dict()
UnboundLocalError: local variable 'doc' referenced before assignment

